### ISSUE TITLE
Download child information after clicking on group

### ISSUE THREAD

**Issue by RobertoAlvarezCeballos** [thoughtbot/expandable-recycler-view#145]
Hi,

Has anyone tried to make it work on demand, so I know the main groups and the number of childs, but to get the information of the child I need to make a second request after the user clicks on the parent row. 

Thanks.

**Comment by tjwpdl** [comment]
I understand that this library allows you to collapse a 2-dimensional list into 1 dimension, allowing you to fold the list at its branches.
So although it may be as simple as overriding 1 of the methods in the adapter, I suspect it may not be possible because you may need to have the full list of items from the start.
Anything is possible, but I think it would take a lot of work.
