### ISSUE TITLE
IndexOutOfBoundsException when back button pressed 

### ISSUE THREAD

**Issue by samirthebti** [thoughtbot/expandable-recycler-view#44]
**This error appear even if i unsure the data is not empty or null in the onSaveInstace method  
The  trace of the  Error :** 

>  java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
>                                                                           at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
>                                                                           at java.util.ArrayList.get(ArrayList.java:308)
>                                                                           at com.thoughtbot.expandablerecyclerview.models.ExpandableGroup.writeToParcel(ExpandableGroup.java:67)
>                                                                           at android.os.Parcel.writeParcelable(Parcel.java:1357)

**Comment by rajsuvariya** [comment]
Please upload the code

**Comment by abdyer** [comment]
I also get this error when `onSaveInstanceState` is called in my fragment in response to navigating to another activity. However, this does not occur when calling the method in response to an orientation change.

**Comment by abdyer** [comment]
In my case, the issue was caused by the first group in the adapter having an empty list of items. Changing that to `null` got rid of the error.

Ideally, [this line](https://github.com/thoughtbot/expandable-recycler-view/blob/master/expandablerecyclerview/src/main/java/com/thoughtbot/expandablerecyclerview/models/ExpandableGroup.java#L61) should be changed to `if (items == null || items.isEmpty()) {` to fix it.

**Comment by rajsuvariya** [comment]
items == null and items.isEmpty() are two different things. If we add this condition then the empty list would be ignored. There is a possibility that the same list is being used somewhere to add the data.

**Comment by kotvertolet** [comment]
There is a solution here: #104
