### ISSUE TITLE
where you call togglegroup method for expand the group programaticy

### ISSUE THREAD

**Issue by moeintav** [thoughtbot/expandable-recycler-view#54]
I want when the activity is open the groups is expandable without user click on them 
but toggle group is not work perfectly

**Comment by rajsuvariya** [comment]
Hi,

Go through this blog to get idea of how flat position changes when group is expanded https://robots.thoughtbot.com/introducing-expandablerecyclerview

Currently, the toggle function takes flat position and that's why you are facing problem

As of now just to serve your purpose,  you can use the following code snippet to expand all the groups programmatically.

```
public void expandGroup (int gPos){
   if(adapter.isGroupExpanded(gPos)){
     return;
   }
   adapter.toggleGroup(gPos);
 }

```

and then call this function in bottom top approach so that you don't have to deal with flat position

```
for (int i = adapter.getGroups().size()-1; i >=0 ; i--) {
   expandGroup(i);
}
```

**Comment by moeintav** [comment]
thank you I am understand and it is work perfectly.
